# Generated by Django 5.2.2 on 2025-08-24 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perspective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('financial', 'Financial'), ('customer', 'Customer'), ('internal_processes', 'Internal Processes'), ('innovation_learning_growth', 'Innovation, Learning and Growth'), ('sustainability_esg', 'Sustainability and ESG')], default='financial', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('developer', models.CharField(blank=True, max_length=100, null=True)),
                ('system_analyst', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('progress', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('status', models.CharField(choices=[('incoming', 'Incoming'), ('in progress', 'In Progress'), ('outgoing', 'Outgoing'), ('completed', 'Completed'), ('delayed', 'Delayed')], default='incoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsible_person', models.CharField(blank=True, max_length=100, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('beneficiary_division', models.CharField(blank=True, max_length=255, null=True)),
                ('performance_measure', models.TextField(blank=True, null=True)),
                ('quarterly_status', models.JSONField(blank=True, default=dict)),
                ('monthly_progress', models.JSONField(blank=True, default=dict)),
                ('color_status', models.CharField(choices=[('not_started', 'Not Started'), ('green', 'Green - On Schedule'), ('amber', 'Amber - Partly on Schedule'), ('brown', 'Brown - Almost off Schedule'), ('red', 'Red - Out of Schedule')], default='not_started', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StrategicInitiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategic_initiatives_or_activities', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, max_length=50, null=True)),
                ('browser', models.CharField(max_length=50)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('changes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.CharField(blank=True, max_length=100, null=True)),
                ('os', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('credit', 'Credit'), ('ccm', 'Corporate Communications Management'), ('bt', 'Business Technology'), ('ct', 'Cente Tech'), ('btmc', 'BT-Multi Channels'), ('bb', 'Business Banking'), ('itsd', 'IT Service Delivery'), ('legal', 'Legal'), ('finance', 'Finance'), ('ca', 'Credit Administration'), ('hr', 'Human Resource'), ('cbo', 'CBO'), ('btmis', '\tBT-MIS'), ('fm', 'Financial Markets'), ('rm', 'Retail & Microfinance')], max_length=100, unique=True)),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], max_length=3)),
                ('year', models.IntegerField(default=2025)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('green', 'Green - On Schedule'), ('amber', 'Amber - Partly on Schedule'), ('brown', 'Brown - Almost off Schedule'), ('red', 'Red - Out of Schedule')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_tracking', to='prj_tracker.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='strategic_initiatives_or_activities',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prj_tracker.strategicinitiative'),
        ),
        migrations.CreateModel(
            name='StrategicObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategic_objective', models.CharField(blank=True, max_length=512, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('perspective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='prj_tracker.perspective')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to=settings.AUTH_USER_MODEL)),
                ('strategic_initiatives_or_activities', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prj_tracker.strategicinitiative')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='strategic_objective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prj_tracker.strategicobjective'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('role', models.IntegerField(choices=[(1, 'Project Admin'), (2, 'Project Officer'), (3, 'System Admin'), (4, 'Project Manager'), (5, 'Developer'), (6, 'Business Analyst'), (7, 'Technical Lead')], null=True)),
                ('availability_status', models.CharField(blank=True, max_length=100, null=True)),
                ('current_projects_count', models.IntegerField(default=0)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prj_tracker.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='YearlyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('weightage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yearly_plans', to='prj_tracker.division')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='yearly_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='prj_tracker.yearlyplan'),
        ),
        migrations.AddField(
            model_name='perspective',
            name='yearly_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perspectives', to='prj_tracker.yearlyplan'),
        ),
    ]
