# Generated by Django 5.2.5 on 2025-08-26 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prj_tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='strategic_initiatives_or_activities',
            new_name='strategic_initiative',
        ),
        migrations.RenameField(
            model_name='strategicinitiative',
            old_name='strategic_initiatives_or_activities',
            new_name='strategic_initiative_name',
        ),
        migrations.RenameField(
            model_name='strategicobjective',
            old_name='strategic_objective',
            new_name='strategic_objective_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='beneficiary_division',
        ),
        migrations.RemoveField(
            model_name='project',
            name='color_status',
        ),
        migrations.RemoveField(
            model_name='project',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='project',
            name='performance_measure',
        ),
        migrations.RemoveField(
            model_name='project',
            name='responsible_person',
        ),
        migrations.RemoveField(
            model_name='project',
            name='strategic_objective',
        ),
        migrations.RemoveField(
            model_name='project',
            name='yearly_plan',
        ),
        migrations.RemoveField(
            model_name='strategicobjective',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='strategicobjective',
            name='responsible_person',
        ),
        migrations.RemoveField(
            model_name='strategicobjective',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='strategicobjective',
            name='strategic_initiatives_or_activities',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='responsible_person',
        ),
        migrations.AddField(
            model_name='projectprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='strategicinitiative',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strategicinitiative',
            name='performance_measure',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strategicinitiative',
            name='perspective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perspective', to='prj_tracker.perspective'),
        ),
        migrations.AddField(
            model_name='strategicinitiative',
            name='responsible_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsible_person', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='strategicinitiative',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strategicinitiative',
            name='strategic_objective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strategic_objective', to='prj_tracker.strategicobjective'),
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='perspective',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dev_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='progress',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('incoming', 'Incoming'), ('in_progress', 'In Progress'), ('outgoing', 'Outgoing'), ('completed', 'Completed'), ('delayed', 'Delayed')], default='incoming', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='system_analyst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ba_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='status',
            field=models.CharField(choices=[('incoming', 'Incoming'), ('in_progress', 'In Progress'), ('outgoing', 'Outgoing'), ('completed', 'Completed'), ('delayed', 'Delayed')], default='incoming', max_length=20),
        ),
        migrations.AlterField(
            model_name='strategicobjective',
            name='perspective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strategic_objective', to='prj_tracker.perspective'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='availability_status',
            field=models.CharField(blank=True, choices=[('available', 'Available'), ('busy', 'Busy'), ('overloaded', 'Overloaded'), ('on_leave', 'On Leave')], default='available', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.IntegerField(choices=[(1, 'Project Admin'), (2, 'Project Officer'), (3, 'System Admin'), (4, 'Project Manager'), (5, 'Developer'), (6, 'System Analyst')], null=True),
        ),
        migrations.AlterField(
            model_name='yearlyplan',
            name='weightage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BeneficiaryDivisionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_division_sections', to='prj_tracker.division')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='beneficiary_division_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prj_tracker.beneficiarydivisionsection'),
        ),
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('closed', 'Closed')], default='open', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='prj_tracker.project')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyProjectUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_updates', to='prj_tracker.project')),
            ],
        ),
    ]
