# Generated by Django 5.2.5 on 2025-08-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prj_tracker', '0003_auditlog_created_at_auditlog_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perspective',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
