# Generated by Django 5.2.5 on 2025-09-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prj_tracker', '0004_alter_perspective_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='priority_rate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
