# Generated by Django 5.2.5 on 2025-09-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prj_tracker', '0005_project_priority_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='priority_rate',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.IntegerField(choices=[(1, 'Project Admin'), (2, 'Chief Manager'), (3, 'Manager'), (4, 'Developer'), (5, 'Business Analyst'), (6, 'System Analyst'), (7, 'QA'), (8, 'DevOps')], null=True),
        ),
    ]
